#!/usr/bin/env python3
"""
TAST Documentation Regenerator (audit finding #25, design decision D2).

Renders generated markdown from templates under TAST/templates/, injecting a
generated-file header and resolving {{TOKEN}} placeholders from live model
output. Numeric claims about model output never survive as hand-typed literals.

Body-neutrality invariant (D2): --check compares template-rendered BODY to the
committed file's BODY (the generated header is excluded from comparison, since
it carries a commit hash and timestamp that change every render). This lets the
extraction step prove it changed no rendered byte before any token is introduced.

    python TAST/scripts/regen_docs.py --check    # fail on body drift
    python TAST/scripts/regen_docs.py --write    # rewrite bodies + headers
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Tuple

HERE = Path(__file__).resolve().parent
TAST_ROOT = HERE.parent
MODEL_DIR = TAST_ROOT / "model"
TEMPLATES_DIR = TAST_ROOT / "templates"

# (template_rel, output_rel) — output is relative to TAST_ROOT
GENERATION_MAP: List[Tuple[str, str]] = [
    ("README.md.tmpl", "README.md"),
    ("METHODS.md.tmpl", "METHODS.md"),
    ("DECISIONS.md.tmpl", "DECISIONS.md"),
    ("VERSION.md.tmpl", "VERSION.md"),
    ("adversarial_H1_likelihoods.md.tmpl", "adversarial_H1_likelihoods.md"),
    ("model/PRIOR_SENSITIVITY.md.tmpl", "model/PRIOR_SENSITIVITY.md"),
    ("surviving/quantitative_floor.md.tmpl", "surviving/quantitative_floor.md"),
]

HEADER_BEGIN = "<!-- BEGIN TAST GENERATED HEADER"
HEADER_END = "END TAST GENERATED HEADER -->"
HEADER_RE = re.compile(
    r"<!-- BEGIN TAST GENERATED HEADER.*?END TAST GENERATED HEADER -->\n*",
    re.DOTALL,
)
TOKEN_RE = re.compile(r"\{\{\s*([A-Z0-9_]+)\s*\}\}")


def _git_commit() -> str:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=str(TAST_ROOT), stderr=subprocess.DEVNULL, text=True,
        ).strip()
    except Exception:
        return "unknown"


def _utcstamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def make_header(template_rel: str) -> str:
    return (
        f"{HEADER_BEGIN} - DO NOT EDIT THIS FILE DIRECTLY. \n"
        f"  Edit the template: templates/{template_rel}\n"
        f"  Generator: scripts/regen_docs.py   commit: {_git_commit()}   "
        f"rendered(UTC): {_utcstamp()}\n"
        f"  Regenerate: python TAST/scripts/regen_docs.py --write\n"
        f"  {HEADER_END}\n"
    )


def strip_header(text: str) -> str:
    """Remove a generated header block if present, for body-only comparison."""
    return HEADER_RE.sub("", text, count=1)


def resolve_tokens(body: str, tokens: Dict[str, str]) -> Tuple[str, List[str]]:
    """Replace {{TOKEN}} with values. Returns (resolved_body, unresolved_tokens)."""
    unresolved: List[str] = []

    def _sub(m: re.Match) -> str:
        name = m.group(1)
        if name in tokens:
            return str(tokens[name])
        unresolved.append(name)
        return m.group(0)

    return TOKEN_RE.sub(_sub, body), unresolved


def render_template(template_rel: str, tokens: Dict[str, str]) -> Tuple[str, List[str]]:
    tmpl = TEMPLATES_DIR / template_rel
    body = tmpl.read_text(encoding="utf-8")
    body, unresolved = resolve_tokens(body, tokens)
    return make_header(template_rel) + body, unresolved


def _sweep_all() -> List[Tuple[str, float, float, float, bool, str]]:
    """Sweep each constant with a declared range; return rows for PRIOR_SENSITIVITY.md.

    Returns [(cid, lo, hi, max_delta, high_influence, note)]. max_delta is the
    maximum absolute H1-H5 posterior change induced by perturbing the constant
    across its range (holding others fixed), taken over r in {0.05, 0.1, 0.3, 0.5}.
    """
    import yaml  # type: ignore
    import numpy as np  # type: ignore
    sys.path.insert(0, str(MODEL_DIR))
    from bayesian_core import (  # noqa: E402
        HYPOTHESES, RAW_PRIORS, collapse_posterior, load_streams,
    )
    try:
        from __init__ import (  # type: ignore
            set_constant_override, clear_constant_overrides,
        )
    except Exception:
        from model import (  # type: ignore
            set_constant_override, clear_constant_overrides,
        )

    data = yaml.safe_load((TAST_ROOT / "data" / "stipulated_constants.yaml").read_text(encoding="utf-8"))
    streams = load_streams()
    r_values = [0.05, 0.1, 0.3, 0.5]
    # baseline posteriors (no overrides)
    clear_constant_overrides()
    baseline = {r: collapse_posterior(streams, RAW_PRIORS, r)[0] for r in r_values}

    rows: List[Tuple[str, float, float, float, bool, str]] = []
    for c in data.get("constants", []):
        sr = c.get("sweep_range")
        if not sr or len(sr) != 2:
            continue
        cid, lo, hi = c["id"], float(sr[0]), float(sr[1])
        max_delta = 0.0
        for v in np.linspace(lo, hi, 5):
            set_constant_override(cid, float(v))
            for r in r_values:
                try:
                    post, _ = collapse_posterior(streams, RAW_PRIORS, r)
                    d = max(abs(post[h] - baseline[r][h]) for h in HYPOTHESES)
                    if d > max_delta:
                        max_delta = d
                except Exception:
                    pass
        clear_constant_overrides()
        note = ""
        if max_delta < 1e-6:
            note = "mechanism-silent (floor term; does not move H1-H5)"
        elif cid == "collapse_flat_target":
            note = "not inert at intermediate r (audit #31)"
        rows.append((cid, lo, hi, max_delta, max_delta > 0.05, note))
    rows.sort(key=lambda x: -x[3])
    return rows


def _sweep_table_token() -> str:
    rows = _sweep_all()
    if not rows:
        return "_(no constants with a declared sweep_range)_"
    out = ["| constant | sweep range | max |Δposterior| | influence | note |",
           "|---|---|---|---|---|"]
    for cid, lo, hi, md, high, note in rows:
        flag = "**HIGH INFLUENCE**" if high else "low"
        out.append(f"| `{cid}` | [{lo}, {hi}] | {md:.4f} | {flag} | {note} |")
    return "\n".join(out)


def load_tokens() -> Dict[str, str]:
    """Resolve {{TOKEN}} values from live model output.

    Finds #25: the README/METHODS r=0 characterization is generated from the
    current evidence_streams.csv, so it can never again describe a stale
    (pre-Stream-31) configuration. All values derive from collapse_posterior at
    r=0 against RAW_PRIORS.
    """
    sys.path.insert(0, str(MODEL_DIR))
    import math  # noqa: E402
    from bayesian_core import (  # noqa: E402
        HYPOTHESES, RAW_PRIORS, collapse_posterior, load_streams,
    )
    streams = load_streams()
    post0, _ = collapse_posterior(streams, RAW_PRIORS, 0.0)
    n_total = len(streams)
    n_quant = sum(1 for s in streams if s.get("is_quantitative", 1) == 1)

    tokens: Dict[str, str] = {}
    for h in HYPOTHESES:
        tokens[f"R0_{h}"] = f"{post0[h]:.1%}"
        tokens[f"PRIOR_{h}"] = f"{RAW_PRIORS[h]:.1%}"
    # measured divergence between r=0 posterior and RAW_PRIORS (audit #25)
    max_delta = max(abs(post0[h] - RAW_PRIORS[h]) for h in HYPOTHESES)
    kl = sum(post0[h] * math.log(post0[h] / RAW_PRIORS[h]) for h in HYPOTHESES)
    # most-reweighted hypothesis
    ratios = {h: post0[h] / RAW_PRIORS[h] for h in HYPOTHESES}
    h_mr = min(ratios, key=lambda h: ratios[h])  # largest fold-down
    tokens["R0_MAX_DELTA"] = f"{max_delta:.3f}"
    tokens["R0_KL_NATS"] = f"{kl:.3f}"
    tokens["R0_MOST_REWEIGHTED"] = h_mr
    tokens["R0_MR_RATIO"] = f"{ratios[h_mr]:.2f}"
    tokens["N_QUANT_STREAMS"] = str(n_quant)
    tokens["N_TOTAL_STREAMS"] = str(n_total)
    # prior ratio string e.g. 8:15:20:20:47 / 110
    parts = [str(round(RAW_PRIORS[h] * 110)) for h in HYPOTHESES]
    tokens["PRIOR_RATIO_STR"] = ":".join(parts) + " / 110"
    # sensitivity sweep table for PRIOR_SENSITIVITY.md (group 9)
    tokens["SWEEP_TABLE"] = _sweep_table_token()
    # floor report tokens for surviving/quantitative_floor.md (group 10)
    try:
        sys.path.insert(0, str(MODEL_DIR))
        from physical_likelihoods import physical_floor_report  # type: ignore
        rep = physical_floor_report()
        tokens["FLOOR_BF"] = f"{rep['log_bayes_factor']:.2f}"
        tokens["FLOOR_NULL"] = str(rep["null_name"])
        tokens["FLOOR_BF_CAVEAT"] = str(rep.get("bf_caveat", "")).replace("\n", " ")
        tokens["FLOOR_INFORMATIVE_LL"] = f"{rep['ll_informative']:.2f}"
        tokens["FLOOR_NONINFORMATIVE_LL"] = f"{rep['ll_noninformative']:.2f}"
        tokens["FLOOR_EXCLUDED"] = "; ".join(
            f"{e['term']} ({e['fact_id']})" for e in rep["excluded"]
        ) or "(none)"
        # Primary observables (audit #39 — interment estimate promoted to lead).
        obs = rep.get("observables", [])
        def _obs(name):
            for o in obs:
                if o["name"].startswith(name):
                    return o
            return None
        interment = _obs("ABG NYC interment")
        if interment:
            tokens["FLOOR_INTERMENT_VAL"] = str(interment["value"])
            tokens["FLOOR_INTERMENT_SOURCE"] = str(interment["source"])
        # Derived-count provenance (audit #29/#36/#37).
        cnt = rep.get("counts", {})
        tokens["FLOOR_N_SITES"] = str(cnt.get("n_burial_sites", "?"))
        tokens["FLOOR_N_SITES_BASIS"] = str(cnt.get("n_burial_sites_basis", "?"))
        tokens["FLOOR_SITE_KEYS"] = ", ".join(
            f"`{k}`" for k in cnt.get("n_burial_site_keys", [])) or "(none)"
        tokens["FLOOR_N_ADNA"] = str(cnt.get("n_adna_individuals", "?"))
        tokens["FLOOR_N_ADNA_BASIS"] = str(cnt.get("n_adna_basis", "?"))
        tokens["FLOOR_ADNA_ROWS"] = "; ".join(
            f"{sid} +{n} ({why})" for sid, n, why in cnt.get("n_adna_rows", [])) or "(none)"
    except Exception:
        pass

    # Confidence weight sweep (audit #40): tier robustness across each weight's
    # declared plausible range. Separate try/except so a sweep failure doesn't
    # block the rest of the token load.
    try:
        sys.path.insert(0, str(MODEL_DIR))
        from derive_confidence import sweep_weights, _load_spec as _dc_spec  # type: ignore
        import yaml as _yaml  # type: ignore
        dspec = _dc_spec()
        for f in dspec["features"]:
            f["sweep_range"] = [0.25, 0.55] if f["id"] == "source_class" else \
                               [0.20, 0.50] if f["id"] == "re_verifiability" else [0.15, 0.40]
            f["confidence_weight_id"] = f"confidence_weight_{f['id']}"
        _facts = _yaml.safe_load((TAST_ROOT / "data" / "observable_facts.yaml").read_text(encoding="utf-8"))["facts"]
        srows = sweep_weights(dspec, _facts)
        lines = ["| weight | swept range | facts moved | scored | influence |",
                 "|---|---|---|---|---|"]
        for wid, lo, hi, moved, scored, _frag, hi_inf in srows:
            lines.append(f"| `{wid}` | [{lo:.2f}, {hi:.2f}] | {moved} | {scored} | "
                         f"{'**HIGH**' if hi_inf else 'low'} |")
        tokens["CONFIDENCE_SWEEP"] = "\n".join(lines)
    except Exception as e:
        tokens["CONFIDENCE_SWEEP"] = f"_(sweep unavailable: {e})_"
    return tokens


def _output_path(output_rel: str) -> Path:
    return TAST_ROOT / output_rel


def run_check(tokens: Dict[str, str]) -> Tuple[bool, List[str]]:
    drift: List[str] = []
    for tmpl_rel, out_rel in GENERATION_MAP:
        out = _output_path(out_rel)
        if not out.exists():
            drift.append(f"{out_rel}: output missing")
            continue
        committed_body = strip_header(out.read_text(encoding="utf-8"))
        rendered, unresolved = render_template(tmpl_rel, tokens)
        rendered_body = strip_header(rendered)
        if committed_body != rendered_body:
            drift.append(
                f"{out_rel}: body drift — this generated file was edited directly. "
                f"Edit the template templates/{tmpl_rel} instead, then run "
                f"`python TAST/scripts/regen_docs.py --write`."
            )
        if unresolved:
            drift.append(f"{out_rel}: unresolved tokens {unresolved}")
    return (len(drift) == 0), drift


def run_write(tokens: Dict[str, str]) -> List[str]:
    written: List[str] = []
    for tmpl_rel, out_rel in GENERATION_MAP:
        rendered, _ = render_template(tmpl_rel, tokens)
        out = _output_path(out_rel)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(rendered, encoding="utf-8")
        written.append(out_rel)
    return written


def main() -> int:
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
    parser = argparse.ArgumentParser(description="TAST documentation regenerator")
    parser.add_argument("--check", action="store_true", help="fail on body drift")
    parser.add_argument("--write", action="store_true", help="rewrite generated files")
    args = parser.parse_args()

    if not args.check and not args.write:
        parser.error("specify --check or --write")

    tokens = load_tokens()
    if args.write:
        written = run_write(tokens)
        print(f"Wrote {len(written)} generated files:")
        for w in written:
            print(f"  {w}")
        # after write, verify check passes
        ok, drift = run_check(tokens)
        print(f"post-write check: {'OK' if ok else 'DRIFT'}")
        return 0 if ok else 1

    ok, drift = run_check(tokens)
    print(f"templates: {len(GENERATION_MAP)}  tokens defined: {len(tokens)}")
    if ok:
        print("No body drift. All generated files match their templates.")
        return 0
    print("DRIFT detected:")
    for d in drift:
        print("  " + d)
    print("\nRemediation: python TAST/scripts/regen_docs.py --write")
    return 1


if __name__ == "__main__":
    sys.exit(main())
